Add .editorconfig and format code style
substrate-developer-hub/substrate-node-template pull request #115
Opened 2020-12-05 23:01 UTC by chenzongxiong

2020-12-07 19:01 UTC, danforbes commented on .editorconfig
> +max_line_length=120
I double-checked with others on this. I think we should enforce a maximum line length of 100-characters.

```suggestion
max_line_length=100
```

2020-12-07 19:02 UTC, danforbes requested changes
Thank you so much! This is a great contribution :pray:

2020-12-09 11:32 UTC, chenzongxiong commented on .editorconfig
> +max_line_length=120
From substrate documentation: 
```
Lines should be longer than 100 characters long only in exceptional circumstances and certainly no longer 
than 120. For this purpose, tabs are considered 4 characters wide.
```

Should I fix the line length long than 100?

2020-12-09 13:17 UTC, danforbes commented on .editorconfig
> +max_line_length=120
I think that would be the right course of action in this case. I'm happy to help with that or answer any questions you have along the way. You may want to look into using a tool like `cargo fmt` to help do this for you.

2020-12-10 23:56 UTC, danforbes approved these changes
Thank you so much!

2020-12-10 23:57 UTC, merged