Update for use on GitHub Codespaces
substrate-developer-hub/substrate-node-template pull request #444
Opened 2023-06-07 11:57 UTC by hummusonrails

In this PR, the `devContainer.json` file is updated to be used with Codespaces and the following additions are made:

* Fetch a pre-built binary of the node-template from Docker Hub
* Make the binary available in /usr/local/bin
* Add a Dockerfile.build so that the binary can be rebuilt for new updates and include instructions on how to publish it to Docker Hub
* Updates the README to include instructions and a link to Codespaces (note: the badge link won't work until this is published)

2023-06-07 12:26 UTC, NukeManDan commented
There is a CI job for every polkadot release that generates a PR to updated this repo from upstream, IMHO PRs should _only_ update upstream and then propagate here via that CI job. 

Could be the CI needs to know about these new files for that to work though :shrug:

2023-06-07 12:27 UTC, oleg-plakida commented
Ci/Cd could create and push image with node-tamplate binary or any other image to 'https://hub.docker.com/u/paritytech'. Let me know if this makes sense.

2023-06-07 12:28 UTC, oleg-plakida approved these changes

2023-06-07 15:21 UTC, TriplEight requested changes
Everything's good, just some improvements.

2023-06-07 15:21 UTC, TriplEight commented on .devcontainer/devcontainer.json
> +  "postCreateCommand": "sudo sh -c 'docker run --rm hummusonrails/substrate-node-template-linux-binary cat /usr/local/bin/node-template > /usr/local/bin/node-template && chmod +x /usr/local/bin/node-
It's better to use an image sourced from paritytech dockerhub registry. And automate its' creation via CI.

2023-06-07 15:21 UTC, TriplEight commented on Dockerfile.build
> +# Dockerfile.build
`Dockerfile` is sorta extension, so [better](https://github.com/paritytech/ci_cd/wiki/Policies-and-Processes:-Dockerfiles-naming-convention) name it `build.Dockerfile`, otherwise IDEs will not recognize it.

2023-06-07 15:21 UTC, TriplEight commented on Dockerfile.build
> +# 3. Push the image to Docker Hub: docker push your-username/your-image-name
```suggestion
# 3. Push the image to Docker Hub: docker push your-username/your-image-name

```

2023-06-07 15:21 UTC, TriplEight commented on Dockerfile.build
> +    && rm -rf /var/lib/apt/lists/*
```suggestion
    libssl1.1 && \
# apt clean up
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
```

2023-06-07 15:21 UTC, TriplEight commented on Dockerfile.build
> +RUN apt-get update && apt-get install -y \
```suggestion
# Working directory
WORKDIR /usr/local/bin

# Copy your binary
COPY ./target/debug/node-template .

RUN chmod +x node-template && \
# Install dependencies
    apt-get update && apt-get install -y \
```

2023-06-07 15:21 UTC, TriplEight commented on Dockerfile.build
> +RUN chmod +x node-template
```suggestion
```

every `RUN` creates another layer and the image ends up being thicker.

2023-06-15 09:27 UTC, sacha-l commented on .devcontainer/devcontainer.json
> +  "postCreateCommand": "sudo sh -c 'docker run --rm hummusonrails/substrate-node-template-linux-binary cat /usr/local/bin/node-template > /usr/local/bin/node-template && chmod +x /usr/local/bin/node-
has this been resolved?

2023-08-01 23:53 UTC, NukeManDan commented on README.md
I still vote upstream too for these files, the README will be clobbered by the CI auto-updates and managing two copies as an anti-pattern :grimacing: 

Can this PR be applied upstream such that it is useful there too? If not, at leat the hidden dir inside the template repo should copy over.

2024-06-26 13:52 UTC, closed without merging

2024-06-26 13:53 UTC, Gesge commented
What's up guy?This is my automatic reply~ With the purpose of enjoying the holiday,I did this auto-reply~Please wait a while but no too long.As soon as I saw it,turn back to your letter~~~